### ISSUE TITLE
User Can Search For A Cryptocurrency

### ISSUE THREAD

**Issue by nickkniola** [nickkniola/ajax-project#1]
## 💰 Motivation

Users want to have the ability to type in a cryptocurrency for easy access.

## 📐 Plan

Create a search input, button, and make GET request for searched cryptocurrency data from API, storing in data object.

## 🖼️ Wireframe

(https://www.figma.com/file/gpDf3uzsXtuBnSg0kynKUN/Cryptocurrency-Project?node-id=0%3A1)

## Functionality

When the user types in the text field and presses the search button, the data is retrieved.

## ✅ Task List

- [x] Create title header
- [x] Create mobile nav bar
- [x] Create text field and search button
- [x] Create sample card for searched cryptocurrency
- [x] Create JavaScript data model
- [x] Access the CoinGecko API to retrieve cryptocurrency data
- [x] Store relevant name/symbol data in data model
- [x] Recreate HTML sample card with createElement() method in JavaScript, accessing data of cryptocurrency name from data model
- [x] Create search functionality which triggers creation of card
- [x] Deal with searching for multiword cryptocurrencies
- [x] Add fullscreen functionality for card in main view
- [x] Fix bugs
