### ISSUE TITLE
User Can View The Current Price

### ISSUE THREAD

**Issue by nickkniola** [nickkniola/ajax-project#2]
## 💰 Motivation

Users want to see the current value of the cryptocurrency they are searching for.

## 📐 Plan

Have the html card fill with current value for the search cryptocurrency from data object.

## 🖼️ Wireframe

(https://www.figma.com/file/gpDf3uzsXtuBnSg0kynKUN/Cryptocurrency-Project?node-id=0%3A1)

## Functionality

When user searches, the current crypto and price appears in the card.

## ✅ Task List

- [x] Add the current price for the cryptocurrency from the Coin Gecko API to the data model on 'load'
- [x] Edit the cardCreator function to add the actual current price as textContent
- [x] Stylize the card text in regular view and fullscreen view
- [x] Add spinning wheel GIF while crypto search is loading
- [x] Fix all bugs
