### ISSUE TITLE
User Can View Past Prices of Cryptocurrency

### ISSUE THREAD

**Issue by nickkniola** [nickkniola/ajax-project#3]
## 💰 Motivation

Users want to see the past values of the cryptocurrency they are searching for (1 week ago, 1 month ago, 3 months ago, 6 months ago, 1 year ago, 5 year ago).

## 📐 Plan

Have the html card fill with past values for the search cryptocurrency from data object.

## 🖼️ Wireframe

(https://www.figma.com/file/gpDf3uzsXtuBnSg0kynKUN/Cryptocurrency-Project?node-id=0%3A1)

## Functionality

When user searches, the past crypto and price appears in the card.

## ✅ Task List
- [x] Create function to generate a date for previous week, previous month, 3 months ago, 6 months ago, last year, 5 years ago
- [x] Call the findPastPrice() function for each date to get the past prices of the cryptocurrency
- [x] Add past prices to the data object
- [x] Add paragraph elements with past prices referenced from data object to cardCreator() function
- [x] Have those paragraph elements only appear when card is full screen
- [x] Fix any bugs
