### ISSUE TITLE
User Can Favorite A Cryptocurrency

### ISSUE THREAD

**Issue by nickkniola** [nickkniola/ajax-project#4]
## 💰 Motivation

Users will want to be able to save favorites for easy access when revisiting page.

## 📐 Plan

Have favorited currency data appear in Favorites section and store in local storage.

## 🖼️ Wireframe

(https://www.figma.com/file/gpDf3uzsXtuBnSg0kynKUN/Cryptocurrency-Project?node-id=0%3A1)

## Functionality

When user favorites a crypto, the crypto is added and saved to the favorites section. When the user first opens the page, the updated prices appear in favorites section.

## ✅ Task List

- [x] Add event listener which triggers when the heart icon is clicked
- [x] Create functionality which pushes the current data object into a data object of objects
- [x] Save data object to local storage
- [x] Have heart change color when favorited
- [x] Add header for Favorites section of page
- [x] Referencing the data array, render mini cards using document.createElement() in bottom half of screen
- [x] When heart button is clicked have the favorited crypto appear in Favorites section
- [x] Stylize the mini cards 
- [x] Make mini cards expandable
- [x] Fix all bugs
