### ISSUE TITLE
User Can Remove A Cryptocurrency from Favorites 

### ISSUE THREAD

**Issue by nickkniola** [nickkniola/ajax-project#5]
## 💰 Motivation

Users will want to be able to remove favorites when they no longer want to see that cryptocurrency in their list of favorites

## 📐 Plan

Have favorited currency data removed from Favorites section and delete from local storage.

## 🖼️ Wireframe

(https://www.figma.com/file/gpDf3uzsXtuBnSg0kynKUN/Cryptocurrency-Project?node-id=0%3A1)

## Functionality

When user clicks the remove button, the current crypto card is removed from the favorites section.

## ✅ Task List

- [x] Delete the property of the unfavorited item from data object which onload will update localstorage automatically with updated data object
- [x] Create functionality which uses the remove() method to remove the unfavorited mini card element if heart icon in main searched card is clicked and favorite is false
- [x] Create functionality which uses the remove() method to remove the unfavorited mini card element if heart icon of containing mini card is clicked
- [x] Design a separate view for a 'Favorites' page
- [x] Fix all bugs
